# -*- coding: utf-8 -*-

explain = {6901237:
               [{'keyword': 'If I fits, I sits.',
                 'type': 'context',
                 'explain': [{'type': 'image', 'content': 'http://www.roflcat.com/images/cats/If_It_Fits_I_Sits.jpg'},
                             {'type': 'image', 'content': 'http://cdn.cutestpaw.com/wp-content/uploads/2012/09/l-If-it-fits-I-sits.jpg'},
                             {'type': 'image', 'content': 'https://www.strongspace.com/postfarm/public/postfarm/uploads-2.0/l/liquidcat.jpg'},
                            ],
                },
               ],
           6894177:
               [{'keyword': 'Regular Show',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '在卡通頻道播放的一部美國卡通'},
                             {'type': 'image', 'content': 'http://4.bp.blogspot.com/-jvjD-_n8OvQ/UQBS6G_u_UI/AAAAAAAAAAc/I_K255qKV8o/s1600/regular-show-8.jpg'},
                             {'type': 'image', 'content': 'http://7.blog.xuite.net/7/7/0/7/18751617/blog_1004711/txt/66516007/1.png'}
                            ],
                },
                {'keyword': "I'm loving it.",
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '麥當勞的一句 slogan'},
                             {'type': 'image', 'content': 'http://manandyung.files.wordpress.com/2011/01/mcdonalds-logo.jpg'}
                            ],
                },
                {'keyword': 'pick up line',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '把妹時說的第一句話'},
                            ],
                },
               ],
           6900723:
               [{'keyword': 'Scumbag Steve',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '是一個 meme ，這個人做了很多混帳事，大家幫他取名叫 Steve 。'},
                             {'type': 'image', 'content': 'http://d24w6bsrhbeh9d.cloudfront.net/photo/3434237_700b.jpg'},
                             {'type': 'image', 'content': 'http://d24w6bsrhbeh9d.cloudfront.net/photo/4052288_700b.jpg'},
                             {'type': 'image', 'content': 'http://d24w6bsrhbeh9d.cloudfront.net/photo/2756795_700b.jpg'},
                            ],
                },
               ],
           6905123:
               [{'keyword': 'Bruce Willis',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '布魯斯威利，一位美國電影明星，代表作是《終極警探》與《靈異第六感》。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Bruce_Willis_by_Gage_Skidmore.jpg/200px-Bruce_Willis_by_Gage_Skidmore.jpg'},
                            ],
                },
                {'keyword': 'Arnold Schwarzenegger',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '阿諾·史瓦辛格，一位美國電影明星，代表作是《魔鬼終結者》與《魔鬼複製人》。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/SchwarzeneggerJan2010.jpg/220px-SchwarzeneggerJan2010.jpg'},
                            ],
                },
                {'keyword': 'Sylvester Stallone',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '席維斯·史特龍，一位美國電影明星，代表作是《洛基》與《第一滴血》。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Sylvester_Stallone_by_Gage_Skidmore.jpg/220px-Sylvester_Stallone_by_Gage_Skidmore.jpg'},
                            ],
                },
               ],
           6906012:
               [{'keyword': 'Asian',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '亞洲人'},
                            ],
                },
                {'keyword': 'Racist',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '種族歧視的人'},
                            ],
                },
                {'keyword': 'Motherfucker',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '罵人的髒話，一般翻作 "王八蛋" 。'},
                            ],
                },
               ],
           6908118:
               [{'keyword': 'Pepper-spraying Cop',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '在 2011 年 11 月時，一群美國戴維斯加大的學生在抗議活動中被警察用辣椒槍掃射，引起眾怒，以致在網路上爆紅，成為眾所皆知的事件。'},
                             {'type': 'image', 'content': 'http://i0.kym-cdn.com/photos/images/newsfeed/000/203/420/UCDavis_pepperspray.jpg?1321852699'},
                            ],
                },
               ],
           6903712:
               [
               ],
           6905118:
               [{'keyword': 'LOL',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '是 Laugh Out Loud 的縮寫，大笑的意思，相近於 "XDD" 。'},
                            ],
                },
               ],
           6907719:
               [{'keyword': 'Power Ranger',
                 'type': '',
                 'explain': [{'type': 'text', 'content': '是一部美國的真人動作兒童電視劇，改編自日本卡通製作而成的電視影集。'},
                             {'type': 'image', 'content': 'http://www.tylertarver.com/wp-content/uploads/2011/06/Mighty-Morphin-Power-Rangers.jpg'},
                            ],
                },
               ],
           6902744:
               [{'keyword': 'motivation',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '動機、動力'},
                            ],
                },
               ],
           6892209:
               [{'keyword': 'Conspiracy Keanu',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '是一個 meme ，講著一些陰謀論的東西，通常是瞎扯，但有時候也會講出滿有道理的陰謀。裡面的男人是基諾李維。'},
                             {'type': 'image', 'content': 'http://i2.kym-cdn.com/photos/images/newsfeed/000/202/489/what-if-i-am-retarded-but-my-parents-payed-everyone-to-play-along-so-i-could-be-happy.jpg'},
                             {'type': 'image', 'content': 'http://i0.kym-cdn.com/photos/images/newsfeed/000/205/893/35cake.jpg'},
                             {'type': 'image', 'content': 'http://t.qkme.me/35k23f.jpg'},
                            ],
                },
                {'keyword': 'Sticker',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '貼紙'},
                            ],
                },
                {'keyword': 'Made in China',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '中國製品'},
                            ],
                },
               ],
           6899916:
               [{'keyword': 'Alert',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '警告'},
                            ],
                },
                {'keyword': 'Ink',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '墨水'},
                            ],
                },
               ],
           6902281:
               [{'keyword': 'Star Wars',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '星際大戰，是美國導演兼編劇喬治·盧卡斯所構思拍攝的一系列科幻電影。'},
                             {'type': 'image', 'content': 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQHQB-Ms41aKg_XUycm0IxY-yxfylfQxsYxc8beBoxKaZxohRNB'},
                            ],
                },
                {'keyword': 'Family Guy',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '蓋酷家庭，講述一個家庭裡發生大小事的美國卡通。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/en/1/1c/Griffin_family.png'},
                            ],
                },
                {'keyword': 'Princess Leia',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '莉雅公主，是電影星際大戰中重要的人物，路克·天行者的雙胞胎妹妹。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/zh/thumb/c/c7/PrincessLeia.jpg/220px-PrincessLeia.jpg'},
                            ],
                },
                {'keyword': 'Lois Griffin',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '蓋酷家庭裡的女主角，是媽媽的角色。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Lois_Griffin.png/170px-Lois_Griffin.png'},
                            ],
                },
                {'keyword': 'Han Solo',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '韓蘇洛，是電影星際大戰中重要的人物，反抗軍同盟最偉大的英雄之一。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/en/thumb/f/f4/HanSolo.jpg/200px-HanSolo.jpg'},
                            ],
                },
                {'keyword': 'Peter Griffin',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '蓋酷家庭裡的男主角，是爸爸的角色。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Peter_Griffin.png/220px-Peter_Griffin.png'},
                            ],
                },
                {'keyword': 'Stormtrooper',
                 'type': 'context',
                 'explain': [{'type': 'text', 'content': '突擊兵，是電影星際大戰中的複製人，接受白卜庭議長的指令。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/13/March_of_Imperial_Soldiers.jpg/250px-March_of_Imperial_Soldiers.jpg'},
                            ],
                },
               ],
           6904755:
               [{'keyword': 'Suicide',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '自殺'},
                            ],
                },
                {'keyword': 'Veteran',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '退伍軍人'},
                            ],
                },
                {'keyword': 'Kneel',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '跪倒'},
                            ],
                },
                {'keyword': 'Monument',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '紀念碑'},
                            ],
                },
                {'keyword': 'Sob',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '嗚咽、哭泣'},
                            ],
                },
                {'keyword': 'Shelter',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '遮蓋物、避難所'},
                            ],
                },
                {'keyword': 'Buzz Lightyear',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '巴斯光年，是《玩具總動員》這部卡通電影中的主要角色。'},
                             {'type': 'image', 'content': 'http://pic6.nipic.com/20100409/3045667_115847069751_2.jpg'},
                            ],
                },
                {'keyword': 'Impound',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '拘留'},
                            ],
                },
                {'keyword': 'Afford',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '擔負得起'},
                            ],
                },
                {'keyword': 'Anniversary',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '週年紀念日'},
                            ],
                },
                {'keyword': 'Ceremony',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '典禮'},
                            ],
                },
                {'keyword': 'World Trade Center',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '紐約世貿，因 911 事件而被摧毀。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Wtc_arial_march2001.jpg/225px-Wtc_arial_march2001.jpg'},
                            ],
                },
                {'keyword': 'Alabama',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '美國阿拉巴馬州'},
                            ],
                },
                {'keyword': 'Tornado',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '龍捲風'},
                            ],
                },
                {'keyword': 'Alcoholic',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '酒鬼'},
                            ],
                },
               ],
           6901991:
               [{'keyword': '',
                 'type': '',
                 'explain': [{'type': '', 'content': ''},
                             {'type': '', 'content': ''},
                            ],
                },
                {'keyword': '',
                 'type': '',
                 'explain': [{'type': '', 'content': ''},
                             {'type': '', 'content': ''},
                            ],
                },
               ],
           6900181:
               [{'keyword': 'Gotta',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '總得'},
                            ],
                },
                {'keyword': 'Miss',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '想念；失誤'},
                            ],
                },
               ],
           6902207:
               [{'keyword': 'Respect',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '尊敬'},
                            ],
                },
                {'keyword': 'Religion',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '宗教'},
                            ],
                },
                {'keyword': 'Muhammad Ali',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '穆罕默德·阿里，一位美國拳擊手，這個世界上最偉大的拳手之一。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/200px-Muhammad_Ali_NYWTS.jpg'},
                            ],
                },
                {'keyword': 'Hollywood',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '好萊塢，美國許多著名電影公司設立於此。'},
                             {'type': 'image', 'content': 'http://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/HollywoodSign.jpg/250px-HollywoodSign.jpg'},
                            ],
                },
                {'keyword': 'PBUH',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '是 Peace Be Upon Him 的縮寫，是先知穆罕默德的意思。'},
                            ],
                },
               ],
           6898899:
               [
               ],
           6892324:
               [
               ],
           6891914:
               [{'keyword': 'Exam',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '考試'},
                            ],
                },
                {'keyword': 'Religious',
                 'type': 'phrase',
                 'explain': [{'type': 'text', 'content': '虔誠的'},
                            ],
                },
               ],
          }

